#!/bin/bash
# Description: Package Manager
set -Ee

function _install {
    case $_DISTRO_BASE in
        ubuntu)
            _tool _apt
            [ -z $2 ] || _ppa $2
            _apt $1
            ;;
        centos)
            _tool _yum
            _yum $1
            ;;
        *)
            exit_with_error
            ;;
    esac
}

function _update {
    case $_DISTRO_BASE in
        ubuntu)
            _tool _apt
            _apt_update
            ;;
        centos)
            _tool _yum
            _yum_update
            ;;
        *)
            exit_with_error
            ;;
    esac
}
