#!/bin/bash
# Description: Linux UFW (Firewall)
set -Ee

UFW_IPV4='to 0.0.0.0/0'

systemctl is-active --quiet iptables && _run "[firewall] Service ${Yellow}iptables${Normal} Stop" systemctl stop iptables
systemctl is-active --quiet iptables && _run "[firewall] Service ${Yellow}iptables${Normal} Disable" systemctl disable iptables

systemctl is-active --quiet firewalld && _run "[firewall] Service ${Yellow}firewalld${Normal} Stop" systemctl stop firewalld
systemctl is-active --quiet firewalld && _run "[firewall] Service ${Yellow}firewalld${Normal} Disable" systemctl disable firewalld

_command_exit csf
_command_exit imunify360-agent
_command ufw

function _ufw_add {
    _run "[firewall] UFW Allow ${Yellow}$1${Normal} $2" ufw allow $UFW_IPV4 port $1 comment "$2"
}
