#!/bin/bash
# Description: Linux UFW (Firewall)
set -Ee

UFW_IPV4='to 0.0.0.0/0'

if command -v iptables >/dev/null 2>&1; then
    _run "[firewall] Service ${Yellow}iptables${Normal} Stop " systemctl stop iptables
    _run "[firewall] Service ${Yellow}iptables${Normal} Disable" systemctl disable iptables
fi

if command -v firewall-cmd >/dev/null 2>&1; then
    _run "[firewall] Service ${Yellow}firewalld${Normal} Stop" systemctl stop firewalld
    _run "[firewall] Service ${Yellow}firewalld${Normal} Disable" systemctl disable firewalld
fi

_command_exit csf
_command_exit imunify360-agent
_command ufw

function _ufw_add {
    _run "[firewall] UFW Allow ${Yellow}$1${Normal} $2" ufw allow $UFW_IPV4 port $1 comment "$2"
}
