#!/bin/bash
# Description: cPanel Account Get All Email *
# Arguments: --domain=cP_DOMAIN
set -e

_tool _cpanel
_domain ${cP_DOMAIN}
local ACCOUNT=${account}
local TMP=/tmp/${HOSTNAME}-${TEMPTEMP}-$1.txt

uapi --output=jsonpretty --user=${ACCOUNT} Email list_pops no_validate=0 skip_main=1 | jq -r '.result.data[].email' >${TMP}
echo "[email] /tmp/ Email: ${yellow}$TMP${normal} ... ${green}done${normal}."
echo "[email] Total Email: ${yellow}$(cat ${TMP} | wc -l)${normal}"
