#!/bin/bash
# Description: cPanel Account Change Pass [All]
# Arguments: --domain=DOMAIN
set -e

_tool _cp
_domain ${DOMAIN}
local ACCOUNT=${account}
local TXT=/tmp/${DOMAIN}-${FDAY}-account-change-pass-all.txt
>${TXT}

PATH_SHADOW=/home/${ACCOUNT}/etc/${DOMAIN}/shadow

_copy ${PATH_SHADOW}
_run "[$1] Create Email Temp ${Yellow}${FDAY}@${DOMAIN}${Normal}" uapi --user=${ACCOUNT} Email add_pop email=${FDAY} password=$PASSWORD quota=0 domain=$DOMAIN skip_update_db=1

LISTS=$(cat /home/${ACCOUNT}/etc/${DOMAIN}/shadow | cut -d':' -f1 | sed '/${FDAY}/d')
for i in $(echo ${LISTS}); do
    local TEMP=$(cat /home/${ACCOUNT}/etc/${DOMAIN}/shadow | grep ${FDAY} | sed 's/'${FDAY}'://g')
    echo "$i:$TEMP" >>${TXT}
done

_msg "[$1] Password All Email ${Yellow}${PASSWORD}${Normal} ${Blue}-->${Normal} ${Color01}Done${Normal}"
cat ${TXT} >$PATH_SHADOW
_run "[$1] Delete Email Temp ${Yellow}${FDAY}@${DOMAIN}${Normal}" uapi --user=${ACCOUNT} Email delete_pop email=${FDAY} domain=$DOMAIN
