#!/bin/bash
# Description: cPanel Account Get Member Mailman
# Arguments: --domain=cP_DOMAIN
set -e

_tool _cpanel
_domain ${cP_DOMAIN}

for list in $(/usr/local/cpanel/3rdparty/mailman/bin/list_lists -b | grep ${cP_DOMAIN}); do
    echo "[mailman] Member for ${yellow}$list${normal}."
    /usr/local/cpanel/3rdparty/mailman/bin/list_members $list
done
exit 0
