#!/bin/bash
# Description: cPanel Account Filter [SPAM] remove [All]
# Arguments: --domain=DOMAIN
set -e

_tool _cp
_domain ${DOMAIN}
local ACCOUNT=${account}

ls -d /home/${ACCOUNT}/mail/${DOMAIN}/*/ | awk 'BEGIN {
}
{
tcmd = "test -d " $1
if(!system(tcmd)){
split($1,MyArray,"/")
print MyArray[6] "@" MyArray[5]
}
}
' | while read Email; do
    User="$(echo "${Email}" | cut -d'@' -f1)"
    Domain="$(echo "${Email}" | cut -d'@' -f2)"
    Account="$(cat /etc/userdomains | grep "${Domain}" | cut -d' ' -f2)"
    _run "[$1] Filter remove ${Yellow}$Email${Normal} -- Move Subject [SPAM] To Junk" uapi --user=$ACCOUNT Email delete_filter account=$Email filtername="Move Subject [SPAM] To Junk"
done
