#!/bin/bash
# Description: cPanel Account Get Member Mailman
# Arguments: --domain=DOMAIN
set -e

_tool _cp
_domain ${DOMAIN}
local TRASH=/tmp/${FDAY}

for list in $(/usr/local/cpanel/3rdparty/mailman/bin/list_lists -b | grep ${DOMAIN}); do
    _msg "[$1] List ${Yellow}$list${Normal} ${Blue}-->${Normal} ${Yellow}${TRASH}-$list.txt${Normal}"
    /usr/local/cpanel/3rdparty/mailman/bin/list_members $list >${TRASH}-$list.txt
done
