#!/bin/bash
# Description: cPanel Account Disk Usage [All]
# Arguments: --domain=DOMAIN
set -e

_tool _cp
_domain ${DOMAIN}
ACCOUNT=${account}
local TXT=/tmp/${DOMAIN}-${FDAY}-account-disk-usage.txt
>${TXT}

ls -d /home/${ACCOUNT}/mail/${DOMAIN}/*/ | awk 'BEGIN {
}
{
tcmd = "test -d " $1
if(!system(tcmd)){
split($1,MyArray,"/")
print MyArray[6] "@" MyArray[5]
}
}
' | while read Email; do
    Domain="$(echo "${Email}" | cut -d'@' -f2)"
    Account="$(cat /etc/userdomains | grep "${Domain}" | cut -d' ' -f2)"
    User="$(echo "${Email}" | cut -d'@' -f1)"
    Diskused=$(
        uapi --user=${Account} Email get_disk_usage user=${User} domain=${Domain} | grep diskused | awk '{print $2}' | sed "s/^'//;s/'$//"
    )
    echo -e "[$1] ${Yellow}${Domain}${Normal} - [email] ${Yellow}${Email}${Normal} - [disk_used] ${Yellow}${Diskused}${Normal} MB" >>${TXT}
done

cat ${TXT}
_run "[$1] File ${Yellow}${TXT}${Normal}" cat ${TXT}
