#!/bin/bash
# Description: cPanel Account Disk Usage [All] *
# Arguments: --domain=cP_DOMAIN
set -e

_tool _cpanel
_domain ${cP_DOMAIN}
ACCOUNT=${account}

TEMP_ACCOUNT_DISK_USAGE=/tmp/${cP_DOMAIN}-${TEMPTEMP}-account-disk-usage.txt
>${TEMP_ACCOUNT_DISK_USAGE}

ls -d /home/${ACCOUNT}/mail/${cP_DOMAIN}/*/ | awk 'BEGIN {
}
{
tcmd = "test -d " $1
if(!system(tcmd)){
split($1,MyArray,"/")
print MyArray[6] "@" MyArray[5]
}
}
' | while read Email; do
    Domain="$(echo "${Email}" | cut -d'@' -f2)"
    Account="$(cat /etc/userdomains | grep "${Domain}" | cut -d' ' -f2)"
    User="$(echo "${Email}" | cut -d'@' -f1)"
    Diskused=$(
        uapi --user=${Account} Email get_disk_usage user=${User} domain=${Domain} | grep diskused | awk '{print $2}' | sed "s/^'//;s/'$//"
    )
    echo -e "[domain] ${yellow}${Domain}${normal} - [email] ${yellow}${Email}${normal} - [disk_used] ${yellow}${Diskused}${normal} MB ${green}... done.${normal}" >>${TEMP_ACCOUNT_DISK_USAGE}
done

cat ${TEMP_ACCOUNT_DISK_USAGE}
_run "[domain] File ${yellow}${TEMP_ACCOUNT_DISK_USAGE}${normal}" cat ${TEMP_ACCOUNT_DISK_USAGE}
