#!/bin/bash
# Description: cPanel Account Get Domain Owner
# Arguments: --domain=DOMAIN
set -e

_tool _cp
_domain ${DOMAIN}
local ACCOUNT=${account}

_msg "[$1] [domain] ${Yellow}${DOMAIN}${Normal} --> [owner] ${Red}${ACCOUNT}${Normal}"
