#!/bin/bash
# Description: cPanel Account Fix 2 Indentities [All]
# Arguments: --domain=DOMAIN
set -e

_tool _cp
_domain ${DOMAIN}
local ACCOUNT=${account}
local TXT=/tmp/${HOSTNAME}-${FDAY}-account-fix-2-indentities.txt

ls -1A /home/${ACCOUNT}/etc/*/*.rcube.db >${TXT}
while read list; do
    _copy ${list}
    _run "[$1] Fix DB ${Yellow}${list}${Normal}" sqlite3 $list 'DELETE FROM identities WHERE identity_id = 2;'
done <${TXT}
