#!/bin/bash
# Description: cPanel Account Bayes Spamassassins [All] *
# Arguments: --domain=cP_DOMAIN
set -e

_tool _cpanel
_domain ${cP_DOMAIN}
ACCOUNT=${account}

# Force a database sync and expiry run
_run "[spam] Force a database sync and expiry run" /usr/local/cpanel/3rdparty/bin/sa-learn --force-expire

## Check file bayes_journal
BAYES_JOURNAL=/home/${ACCOUNT}/.spamassassin/bayes_journal
if [ -f ${BAYES_JOURNAL} ]; then
    _run "[spam] Remove ${yellow}${BAYES_JOURNAL}${normal}" rm -rf ${BAYES_JOURNAL}
else
    echo "[spam] File ${yellow}${BAYES_JOURNAL}${normal} ${red}does not exist${normal}."
fi

## Check file bayes_seen
BAYES_SEEN=/home/${ACCOUNT}/.spamassassin/bayes_seen
if [ -f ${BAYES_SEEN} ]; then
    _run "[spam] Remove ${yellow}${BAYES_SEEN}${normal}" rm -rf ${BAYES_SEEN}
else
    echo "[spam] File ${yellow}${BAYES_SEEN}${normal} ${red}does not exist${normal}."
fi

## Check file bayes_toks
BAYES_TOKS=/home/${ACCOUNT}/.spamassassin/bayes_toks
if [ -f ${BAYES_TOKS} ]; then
    _run "[spam] Remove ${yellow}${BAYES_TOKS}${normal}" rm -rf ${BAYES_TOKS}
else
    echo "[spam] File ${yellow}${BAYES_TOKS}${normal} ${red}does not exist${normal}."
fi

_restart spamd
exit 0
