#!/bin/bash
# Description: cPanel Account IPv6 Disable
# Arguments: --domain=DOMAIN
set -e

_tool _cp
_domain ${DOMAIN}
local ACCOUNT=${account}

_run "[$1] Disable IPv6 of ${Yellow}${DOMAIN}${Normal}" whmapi1 --output=jsonpretty ipv6_disable_account user=$ACCOUNT range='SHARED'
