#!/bin/bash
# Description: cPanel Account Filter [SPAM] [All] *
# Arguments: --domain=cP_DOMAIN
set -e

_tool _cpanel
_domain ${cP_DOMAIN}
ACCOUNT=${account}

ls -d /home/${ACCOUNT}/mail/${cP_DOMAIN}/*/ | awk 'BEGIN {
}
{
tcmd = "test -d " $1
if(!system(tcmd)){
split($1,MyArray,"/")
print MyArray[6] "@" MyArray[5]
}
}
' | while read Email; do
    User="$(echo "${Email}" | cut -d'@' -f1)"
    Domain="$(echo "${Email}" | cut -d'@' -f2)"
    Account="$(cat /etc/userdomains | grep "${Domain}" | cut -d' ' -f2)"
    _run "[filter] Config Filter Email ${yellow}$Email${normal} Move Subject [SPAM] To Junk" uapi --user=$ACCOUNT Email store_filter filtername="Move Subject [SPAM] To Junk" account=$Email action1=save dest1=$home/mail/$Domain/$User/.Junk part1=\$header_subject: match1=matches val1="^\[SPAM]" opt1=or
done
