#!/bin/bash
# Description: cPanel Account Get Domain Owner
# Arguments: --domain=cP_DOMAIN
set -e

_tool _cpanel
_domain ${cP_DOMAIN}
ACCOUNT=${account}

_run "[domain] ${yellow}${cP_DOMAIN}${normal} --> [owner] ${red}${ACCOUNT}${normal}"
