#!/bin/bash
# Description: cPanel Account Get All Email
# Arguments: --domain=DOMAIN
set -e

_tool _cp
_domain ${DOMAIN}
local ACCOUNT=${account}
local TXT=/tmp/${DOMAIN}-${FDAY}-account-get-all-email.txt

uapi --output=jsonpretty --user=${ACCOUNT} Email list_pops no_validate=0 skip_main=1 | jq -r '.result.data[].email' >${TXT}
_msg "[$1] ----- Email: ${Yellow}$TXT${Normal} ${Blue}-->${Normal} ${Green}Done${Normal}"
_msg "[$1] Total Email: ${Yellow}$(cat ${TXT} | wc -l)${Normal}"
