#!/bin/bash
# Description: cPanel Account Backup Shadow
# Arguments: --domain=DOMAIN
set -e

_tool _cp
_domain ${DOMAIN}
local ACCOUNT=${account}

PATH_SHADOW=/home/${ACCOUNT}/etc/${DOMAIN}/shadow

_run "[$1] File ${Yellow}${PATH_SHADOW}.${FDAY}${Normal}" cp ${PATH_SHADOW}{,.${FDAY}}
