#!/bin/bash
# Description: cPanel Account Fix Unlink [All]
# Arguments: --domain=DOMAIN
set -e

_tool _cp
_domain ${DOMAIN}
local ACCOUNT=${account}
local TXT=/tmp/${HOSTNAME}-${FDAY}-account-fix-unlink-all.txt

ls -all /home/${ACCOUNT}/mail/ | awk '$9 ~ /@/' | awk '{print $9, $11;}' | cut -d'/' -f1 >${TXT}

cat ${TXT} | while read Email Domain; do
    Account=$(/scripts/whoowns ${DOMAIN})
    DIR=/home/${Account}/mail/

    if [ -d "${DIR}" ]; then
        cd ${DIR}
        _run "[$1] Unlink ${Yellow}${Email}${Normal}" unlink $Email
    fi
done
