#!/bin/bash
# Description: cPanel Account Change Pass All Email
# Arguments: --domain=cP_DOMAIN
set -e

_tool _cpanel
_domain ${cP_DOMAIN}
ACCOUNT=${account}

TEMP_PASS=/tmp/${cP_DOMAIN}-${TEMPTEMP}-account-change-pass-all-email.txt
>${TEMP_PASS}
PATH_SHADOW=/home/${ACCOUNT}/etc/${cP_DOMAIN}/shadow

_run "[email] Backup File Shadow ${yellow}${PATH_SHADOW}.${TEMPEMAIL}${normal}." cp ${PATH_SHADOW}{,.${TEMPTEMP}}
_run "[email] Create Email Temp ${yellow}${TEMPTEMP}@${cP_DOMAIN}${normal}." uapi --user=${ACCOUNT} Email add_pop email=${TEMPTEMP} password=$PASS quota=0 domain=$cP_DOMAIN skip_update_db=1

LISTS=$(cat /home/${ACCOUNT}/etc/${cP_DOMAIN}/shadow | cut -d':' -f1 | sed '/${TEMPTEMP}/d')
for i in $(echo ${LISTS}); do
    TEMP=$(cat /home/${ACCOUNT}/etc/${cP_DOMAIN}/shadow | grep ${TEMPTEMP} | sed 's/'${TEMPTEMP}'://g')
    echo "$i:$TEMP" >>${TEMP_PASS}
done

echo "[email] Password ${yellow}${PASS}${normal}."
cat ${TEMP_PASS} >$PATH_SHADOW
_run "[email] Delete Email Temp ${yellow}${TEMPTEMP}@${cP_DOMAIN}${normal}." uapi --user=${ACCOUNT} Email delete_pop email=${TEMPTEMP} domain=$cP_DOMAIN
