#!/bin/bash
# Description: cPanel Account Backup Shadow
# Arguments:
set -e

_tool _cpanel

_check ${cP_DOMAIN}

USER=$(/scripts/whoowns ${cP_DOMAIN})

_check ${USER}

PASSPATH=/home/${USER}/etc/${cP_DOMAIN}/shadow

_run "[shadow] backup" cp ${PASSPATH}{,.${TEMPTEMP}}
_run "[shadow]" ls -al /home/${USER}/etc/${cP_DOMAIN}/ | grep "shadow"
