#!/bin/bash
# Description: cPanel Account Backup Shadow *
# Arguments: --domain=cP_DOMAIN
set -e

_tool _cpanel
_domain ${cP_DOMAIN}
ACCOUNT=${account}

PATH_SHADOW=/home/${ACCOUNT}/etc/${cP_DOMAIN}/shadow

_run "[shadow] Backup File Shadow ${yellow}${PATH_SHADOW}.${TEMPTEMP}${normal}" cp ${PATH_SHADOW}{,.${TEMPTEMP}}
