#!/bin/bash
# Description: cPanel check DNS
set -e

_tool _cpanel

TEMPMX=/tmp/${TEMPTEMP}-MX.csv

>${TEMPMX}
awk -F ": " '{print $1}' /etc/userdomains | sed '/: nobody/d' | grep -v salehost >$TEMP.DOMAIN
cat $TEMP.DOMAIN | while read domain; do
    NS=$(dig NS $domain +short | awk 'NR == 1 {print $1}')
    MX=$(dig MX $domain +short | awk 'NR == 1 {print $2}')
    if [ -z $MX ]; then
        IP=none
    else
        IP=$(dig $MX +short | awk 'NR == 1 {print $1}')
    fi
    echo -e "$domain,$MX,$IP,$NS" >>${TEMPMX}
done

_run "[dns] file ${yellow}${TEMPMX}${normal}" cat $TEMPMX
