#!/bin/bash
# Description: cPanel Email Filter [SPAM]
# Arguments: --email=EMAIL
set -e

_tool _cp

User="$(echo "${EMAIL}" | cut -d'@' -f1)"
Domain="$(echo "${EMAIL}" | cut -d'@' -f2)"

_domain ${Domain}
local ACCOUNT=${account}

_run "[$1] Filter ${Yellow}$EMAIL${Normal} -- Move Subject [SPAM] To Junk" uapi --user=$ACCOUNT Email store_filter filtername="Move Subject [SPAM] To Junk" account=$EMAIL action1=save dest1=$home/mail/$Domain/$User/.Junk part1=\$header_subject: match1=matches val1="^\[SPAM]" opt1=or
