#!/bin/bash
# Description: cPanel email change pass all (account)
set -e

_tool _cpanel

_check ${cP_DOMAIN}

USER=$(/scripts/whoowns ${cP_DOMAIN})

_check ${USER}

TEMPEMAIL=${HOSTNAME}${DATE}

PASSPATH=/home/${USER}/etc/${cP_DOMAIN}/shadow
_run "[email] backup file shadow ${yellow}${PASSPATH}{,.${DATE}}${normal}" cp ${PASSPATH}{,.${DATE}}
_run "[email] create email temp ${yellow}${TEMPEMAIL}@${cP_DOMAIN}${normal}" /scripts/addpop ${TEMPEMAIL}@${cP_DOMAIN} ${PASS} 1
LISTUSER=$(cat /home/${USER}/etc/${cP_DOMAIN}/shadow | cut -d':' -f1 | sed '/${TEMPEMAIL}/d')
for i in $(echo ${LISTUSER}); do
    TEMP=$(cat /home/${USER}/etc/${cP_DOMAIN}/shadow | grep ${TEMPEMAIL} | sed 's/${TEMPEMAIL}://g')
    _run "[email] create temp file pass" echo "$i:${TEMP}" >>/tmp/pass
done
_run "[email] set new password ${green}${PASS}${normal}" cat /tmp/pass >${PASSPATH}
_run "[email] delete email temp ${yellow}${TEMPEMAIL}@${cP_DOMAIN}${normal}" /scripts/delpop ${TEMPEMAIL}@${cP_DOMAIN}
