#!/bin/bash
# Description: cPanel Email Fix Dovecot UTF-8
# Arguments: --email=cP_EMAIL
set -e

# if [ -z "$1" ]; then
#     echo Usage: $0 {Email}
#     exit 1
# fi

# cP_EMAIL=$1

_tool _cpanel
_check ${cP_EMAIL}

User="$(echo "${cP_EMAIL}" | cut -d'@' -f1)"
Domain="$(echo "${cP_EMAIL}" | cut -d'@' -f2)"

_domain ${Domain}
ACCOUNT=${account}

DIR=/home/${ACCOUNT}/mail/${Domain}/${User}

if [ -d "${DIR}" ]; then
    cd ${DIR}
else
    echo -e "[dovecot] Folder Email ${yellow}${cP_EMAIL}${normal} does not exist."
    exit 1
fi

cat subscriptions | sed '/INBOX/d;/Sent/d;/Trash/d;/Drafts/d;/spam/d;/Archive/d;/Junk/d' >subscriptions.${TEMPTEMP}

while read name; do
    new_name="$(basename "${name}" | tr "&" "+" | tr "," "/" | iconv -f UTF-7 -t UTF-8)"
    if [ "${name}" != "${new_name}" ]; then
        [ ! -e "${new_name}" ] && mv -T ".${name}" ".${new_name}"
        echo "[dovecot] Folder ${yellow}${name}${normal} was renamed to ${yellow}${new_name}${normal}." || echo "[dovecot] ${yellow}${name}${normal} wasn't renamed!"
    fi
done <subscriptions.${TEMPTEMP}

cat subscriptions | tr "&" "+" | tr "," "/" | iconv -f UTF-7 -t UTF-8 >subscriptions.update
cat subscriptions.update >subscriptions

exit 0
