#!/bin/bash
# Description: cPanel email change pass all (account)
set -e

_tool _cpanel

_check ${cP_DOMAIN}

USER=$(/scripts/whoowns ${cP_DOMAIN})

_check ${USER}

>/tmp/pass

PASSPATH=/home/${USER}/etc/${cP_DOMAIN}/shadow
_run "[email] backup file shadow ${yellow}${PASSPATH}.${TEMPEMAIL}${normal}" cp ${PASSPATH}{,.${TEMPTEMP}}
_run "[email] create email temp ${yellow}${TEMPTEMP}@${cP_DOMAIN}${normal}" uapi --user=$USER Email add_pop email=${TEMPTEMP} password=$PASS quota=0 domain=$cP_DOMAIN skip_update_db=1
LISTUSER=$(cat /home/${USER}/etc/${cP_DOMAIN}/shadow | cut -d':' -f1 | sed '/${TEMPTEMP}/d')
for i in $(echo $LISTUSER); do
    TEMP=$(cat /home/${USER}/etc/${cP_DOMAIN}/shadow | grep ${TEMPTEMP} | sed 's/'${TEMPTEMP}'://g')
    echo "$i:$TEMP" >>/tmp/pass
done
echo "[email] password ${yellow}${PASS}${normal}"
cat /tmp/pass >$PASSPATH
_run "[email] delete email temp ${yellow}${TEMPTEMP}@${cP_DOMAIN}${normal}" uapi --user=$USER Email delete_pop email=${TEMPTEMP} domain=$cP_DOMAIN
