#!/bin/bash
# Description: cPanel Email Fix Dovecot UTF-8
# Arguments: --email=EMAIL
set -e

# if [ -z "$1" ]; then
#     echo Usage: $0 {Email}
#     exit 1
# fi

# EMAIL=$1

_tool _cp

User="$(echo "${EMAIL}" | cut -d'@' -f1)"
Domain="$(echo "${EMAIL}" | cut -d'@' -f2)"

_domain ${Domain}
local ACCOUNT=${account}

DIR=/home/${ACCOUNT}/mail/${Domain}/${User}

if [ -d "${DIR}" ]; then
    cd ${DIR}
    _msg "[$1] ${Yellow}${EMAIL}${Normal} ${Blue}-->${Normal} ${Green}exist${Normal}."
else
    _msg "[$1] Folder Email ${Yellow}${EMAIL}${Normal} does not exist."
    exit_with_error
fi

cat subscriptions | sed '/INBOX/d;/Sent/d;/Trash/d;/Drafts/d;/spam/d;/Archive/d;/Junk/d' >subscriptions.${FDAY}

while read name; do
    new_name="$(basename "${name}" | tr "&" "+" | tr "," "/" | iconv -f UTF-7 -t UTF-8)"
    if [ "${name}" != "${new_name}" ]; then
        [ ! -e "${new_name}" ] && mv -T ".${name}" ".${new_name}"
        _msg "[$1] Folder ${Yellow}${name}${Normal} was renamed to ${Yellow}${new_name}${Normal}." || _mgs "[dovecot] ${Yellow}${name}${Normal} wasn't renamed!"
    fi
done <subscriptions.${FDAY}

cat subscriptions | tr "&" "+" | tr "," "/" | iconv -f UTF-7 -t UTF-8 >subscriptions.update
_run "[$1] Update name ${Yellow}${EMAIL}${Normal}" cat subscriptions.update >subscriptions
