#!/bin/bash
# Description: cPanel config fiter [SPAM] to Junk email
set -e

_tool _cpanel

_check ${cP_EMAIL}

User="$(echo "${cP_EMAIL}" | cut -d'@' -f1)"
Domain="$(echo "${cP_EMAIL}" | cut -d'@' -f2)"
Account="$(cat /etc/userdomains | grep "${Domain}" | cut -d' ' -f2)"

_domain ${Domain}

_run "[filter] ${yellow}${cP_EMAIL}${normal} config move subject [SPAM] to Junk" uapi --user=$Account Email store_filter filtername="Move Subject [SPAM] to Junk" account=$cP_EMAIL action1=save dest1=$home/mail/$Domain/$User/.Junk part1=\$header_subject: match1=matches val1="^\[SPAM]" opt1=or
