#!/bin/bash
# Description: cPanel System Backup
# Arguments:
set -e

_tool _cp

BKDIR="/backup"
# _mount ${BKDIR}
_mkdir ${BKDIR}/${HOSTNAME}
_mkdir ${BKDIR}/${HOSTNAME}/${DATE}

for account in $(cat /etc/userdomains | awk {'print $2'} | sed /nobody/d); do
    _run "[$1] Backup Account ${Yellow}$account${Normal}" /scripts/pkgacct --backup --skiplogs $account ${BKDIR}/${HOSTNAME}/${DATE}/
done

cd ${BKDIR}/${HOSTNAME}/
_run "[$1] Keep Last 3 Backup" ls -lt | tail -n +6 | awk '{print $9}' | xargs rm -rf
