#!/bin/bash
# Description: cPanel System Fix Unlink [All]
# Arguments:
set -e

_tool _cpanel

TEMP_UNLINK_ALLEMAIL=/tmp/${HOSTNAME}-${TEMPTEMP}-system-fix-unlink-all-email.txt

ls -all /home/*/mail/ | awk '$9 ~ /@/' | awk '{print $9, $11;}' | cut -d'/' -f1 >${TEMP_UNLINK_ALLEMAIL}

while read Email Domain; do
    Account=$(/scripts/whoowns $1)
    echo "[unlink] $Email - $Domain - $Account"
    DIR=/home/${Account}/mail/

    if [ -d "${DIR}" ]; then
        cd ${DIR}
        unlink $Email
    else
        _run "[unlink] ${yellow}${Email}${normal} does not exist." echo "[unlink] ${Email} does not exist."
        exit 1
    fi
done <${TEMP_UNLINK_ALLEMAIL}
