#!/bin/bash
# Description: cPanel System Clean Mailman [All]
# Arguments:
set -e

MAINMAN_PATH=/usr/local/cpanel/3rdparty/mailman/archives/private

for i in $(/usr/local/cpanel/3rdparty/mailman/bin/list_lists -b); do

    # Check directory mailing list
    if [ -d ${MAINMAN_PATH}/$i ]; then
        _msg "[$1] ${Yellow}$i${normal} --> ${Green}OK${Normal}."
        _run "[$1] remove exist list" rm -rf ${MAINMAN_PATH}/$i/*
    else
        _msg "[$1] ${Yellow}$i${Normal} --> ${Red}DOES NOT EXIST${Normal}."
    fi

    # Check file mailing list MBOX
    if [ -f ${MAINMAN_PATH}/$i'.mbox'/$i'.mbox' ]; then
        _msg "[$1] mailing list MBOX $i ${Blue}-->${Normal} ${Green}OK${Normal}."
        _msg "" >${MAINMAN_PATH}/$i'.mbox'/$i'.mbox'
    else
        _msg "[$1] mailing list MBOX $i ${Blue}-->${Normal} ${Red}DOES NOT EXIST${Normal}."
        _run "[$1] touch" touch ${MAINMAN_PATH}/$i'.mbox'/$i'.mbox'
        _run "[$1] chown -R mailman.mailman" chown -R mailman.mailman ${MAINMAN_PATH}/$i'.mbox'/$i'.mbox'
    fi
    _run "[$1] Refresh Mailing List $i" /usr/local/cpanel/3rdparty/mailman/bin/arch --wipe $i

    # Permission mailing list
    _run "[$1] chown -R mailman.mailman" chown -R mailman.mailman ${MAINMAN_PATH}/$i
    _run "[$1] chown mailman.nobody" chown mailman.nobody ${MAINMAN_PATH}/$i
    _run "[$1] chmod 710" chmod 710 ${MAINMAN_PATH}/$i
    _run "[$1] Update Mailman Cache." /scripts/update_mailman_cache
done
