#!/bin/bash
# Description: cPanel System Check DNS [All]
# Arguments:
set -e

_tool _cp

local TXT_MXR=/tmp/${HOSTNAME}-${FDAY}-system-check-mxr.csv
local TXT_DNS=/tmp/${HOSTNAME}-${FDAY}-system-check-dns.txt

>${TXT_MXR}
awk -F ": " '{print $1}' /etc/userdomains | sed '/: nobody/d' | grep -v salehost >$TXT_DNS
while read domain; do
    NS=$(dig NS $domain +short | awk 'NR == 1 {print $1}')
    MX=$(dig MX $domain +short | awk 'NR == 1 {print $2}')
    if [ -z $MX ]; then
        IP=none
    else
        IP=$(dig $MX +short | awk 'NR == 1 {print $1}')
    fi
    echo -e "$domain,$MX,$IP,$NS" >>${TXT_MXR}
done <$TXT_DNS

_run "[$1] File ${Yellow}${TXT_MXR}${Normal}." cat $TXT_MXR
