#!/bin/bash
# Description: cPanel System Get All Email
# Arguments:
set -e

_tool _cpanel

TEMP_ALL_EMAIL=/tmp/${HOSTNAME}-${TEMPTEMP}-system-get-all-email-account.txt
>$TEMP_ALL_EMAIL

CP_ACCOUNTS=$(ls -1A /var/cpanel/users/)

for user in $(echo -n $CP_ACCOUNTS); do
    domain=$(grep -i ^dns /var/cpanel/users/$user | cut -d= -f2)
    for dom in $(echo -n "$domain"); do
        PASSWD_FILE="/home/$user/etc/$dom/passwd"
        if [ -f $PASSWD_FILE ] && [ -s $PASSWD_FILE ]; then
            for mail in $(cat $PASSWD_FILE | cut -d":" -f1); do
                echo "$mail@$dom" >>${TEMP_ALL_EMAIL}
            done
        fi
    done
done

TOTAL_EMAIL=$(cat ${TEMP_ALL_EMAIL} | wc -l)

_run "[email] Total Email ${yellow}${TOTAL_EMAIL}${normal}." cat ${TEMP_ALL_EMAIL} | wc -l
