#!/bin/bash
# Description: cPanel System Backup
# Arguments:
set -e

_tool _cpanel

BKDIR="/backup"
_mount ${BKDIR}
_mkdir ${BKDIR}/${HOSTNAME}
_mkdir ${BKDIR}/${HOSTNAME}/${DAY}

for account in $(cat /etc/userdomains | awk {'print $2'}); do
    _run "[backup] Backup Account $account." /scripts/pkgacct --backup --skiplogs $account ${BKDIR}/${HOSTNAME}/${DAY}
done

cd ${BKDIR}/${HOSTNAME}/
_run "[backup] Keep Last 3 Backup." ls -lt | tail -n +6 | awk '{print $9}' | xargs rm -r
