#!/bin/bash
# Description: cPanel System Fix Quota [All]
# Arguments:
set -e

TEMP_ACCOUNT=/tmp/${HOSTNAME}-${TEMPTEMP}-account
TEMP_ACCOUNT_QUOTA=/tmp/${HOSTNAME}-${TEMPTEMP}-account-quota
TEMP_ACCOUNT_QUOTA_NOT_FOUND=/tmp/${HOSTNAME}-${TEMPTEMP}-account-quota-not-found

ls /home/*/etc/*/quota | cut -d'/' -f3 | sort -n >${TEMP_ACCOUNT_QUOTA}
cat /etc/userdomains | awk '{print $2}' | sort -n | sed '/nobody/d' >${TEMP_ACCOUNT}
diff -u ${TEMP_ACCOUNT_QUOTA} ${TEMP_ACCOUNT} | grep -E '^\+' | sed 's/^+//g' | sed '1d' >${TEMP_ACCOUNT_QUOTA_NOT_FOUND}

while IFS= read -r line; do
    echo -n "[fix] Quota ${yellow}$line${normal}."
    domain=$(cat /etc/userdomains | grep $line | cut -d: -f1)
    touch /home/$line/etc/$domain/quota
    echo -n " ... "
    chown $line.mail /home/$line/etc/$domain/quota
    echo "${green}done${normal}"
done <${TEMP_ACCOUNT_QUOTA_NOT_FOUND}
