#!/bin/bash
# Description: cPanel System Fix 2 Indentities [All]
# Arguments:
set -e

_tool _cp

local TXT=/tmp/${HOSTNAME}-${FDAY}-system-fix-2-indentities.txt

ls -1A /home/*/etc/*/*.rcube.db >${TXT}
while read list; do
    _run "[$1] Backup ${Yellow}${list}.${FDAY}${normal}" cp $list{,.${FDAY}}
    _run "[$1] Fix DB ${Yellow}${list}${Normal}" sqlite3 $list 'DELETE FROM identities WHERE identity_id = 2;'
done <${TXT}
