#!/bin/bash
# Description: cPanel System Fix Dovecot UTF-8 All Email
# Arguments:
set -e

_tool _cpanel

TEMP_ALLEMAIL=/tmp/${HOSTNAME}-${TEMPTEMP}-system-fix-dovecot-utf8-all-email.txt

ls -all /home/*/mail/*/*/subscriptions | awk -F"/" '{ print $6,$5 }' | sed s/\ /\@/g >${TEMP_ALLEMAIL}
while read list; do
    echo $list
    ./cp_dovecot_fix_utf8 $list
done <${TEMP_ALLEMAIL}

_run "[dovecot] File ${yellow}${TEMP_ALLEMAIL}${normal}." cat ${TEMPALLEMAIL}
