#!/bin/bash
# Description: cPanel System Clone Server
# Arguments:
set -e

_tool _cp

local PATH_CPANEL=/usr/local/cpanel/base/unprotected/cpanel
local PATH_GIT=https://raw.githubusercontent.com/longmikel/cPanel/master/Brand

[[ -z "${IP_OLD:-}" ]] && _die "${Yellow}IP_OLD${Normal} ${Blue}-->${Normal} ${Red}does not exist${Normal}." # IP Old
[[ -z "${IP_NEW:-}" ]] && _die "${Yellow}IP_NEW${Normal} ${Blue}-->${Normal} ${Red}does not exist${Normal}." # IP New
[[ -z "${HN_OLD:-}" ]] && _die "${Yellow}HN_OLD${Normal} ${Blue}-->${Normal} ${Red}does not exist${Normal}." # Hostname Old
[[ -z "${HN_NEW:-}" ]] && _die "${Yellow}HN_NEW${Normal} ${Blue}-->${Normal} ${Red}does not exist${Normal}." # Hostname New

_run "[$1] Config hostname." hostnamectl set-hostname ${HN_NEW}
_run "[$1] Config IP in file hosts." sed -i "s|${IP_OLD}|${IP_NEW}|g" /etc/hosts
_run "[$1] Config hostname in file hosts." sed -i "s|${HN_OLD} proxx|${HN_NEW} ${ALIAS_NAME}|g" /etc/hosts
_run "[$1] Config MainIP." sed -i "s|${IP_OLD}|${IP_NEW}|g" /var/cpanel/mainip

_run "[$1] Config IP in Basic Webhost." sed -i "s|${IP_OLD}|${IP_NEW}|g" /etc/wwwacct.conf
_run "[$1] Config Hostname in Basic Webhost." sed -i "s|${HN_OLD}|${HN_NEW}|g" /etc/wwwacct.conf
_run "[$1] Config IP for Apache." sed -i "s|${IP_OLD}|${IP_NEW}|g" /var/cpanel/conf/apache/primary_virtual_hosts.conf
_run "[$1] Config Hostname for Apache." sed -i "s|${HN_OLD}|${HN_NEW}|g" /var/cpanel/conf/apache/primary_virtual_hosts.conf
_run "[$1] Enable backup and config backup directory." whmapi1 backup_config_set backupenable=1 backupdir=%2Fbackup%2F${ALIAS_NAME}

_run "[$1] Config CSS." curl ${PATH_GIT}/CSS/style_v2_optimized.css -o ${PATH_CPANEL}/style_v2_optimized.css
_run "[$1] Config WHM Logo." curl ${PATH_GIT}/Images/whm-logo_white.svg -o ${PATH_CPANEL}/images/whm-logo_white.svg
_run "[$1] Config cPanel Logo." curl ${PATH_GIT}/Images/cpanel-logo.svg -o ${PATH_CPANEL}/images/cpanel-logo.svg
_run "[$1] Config Webmail Logo." curl ${PATH_GIT}/Images/webmail-logo.svg -o ${PATH_CPANEL}/images/webmail-logo.svg
