#!/bin/bash
# Description: cPanel System Get All Email
# Arguments:
set -e

_tool _cpanel

local TXT=/tmp/${HOSTNAME}-${TEMPTEMP}-system-get-all-email.txt
>$TXT

CP_ACCOUNTS=$(ls -1A /var/cpanel/users/)

for user in $(echo -n $CP_ACCOUNTS); do
    domain=$(grep -i ^dns /var/cpanel/users/$user | cut -d= -f2)
    for dom in $(echo -n "$domain"); do
        PASSWD_FILE="/home/$user/etc/$dom/passwd"
        if [ -f $PASSWD_FILE ] && [ -s $PASSWD_FILE ]; then
            for mail in $(cat $PASSWD_FILE | cut -d":" -f1); do
                echo "$mail@$dom" >>${TXT}
            done
        fi
    done
done

local TOTAL=$(cat ${TXT} | wc -l)

_msg "[$1] File ${Yellow}${TXT}${Normal} ${Blue}-->${Normal} ${Color01}Done${Normal}"
_msg "[$1] Total Email ${Yellow}${TOTAL}${Normal}"
