#!/bin/bash
# Description: cPanel System Set Site IP
# Arguments:
set -e

IP=$(cat /var/cpanel/mainip)
for user in $(cat /etc/trueuserdomains | cut -d: -f2); do
    /usr/local/cpanel/bin/setsiteip -u $user $IP
done
