#!/bin/bash
# Description: cPanel System Fix Dovecot UTF-8 [All]
# Arguments:
set -e

_tool _cp

local TXT=/tmp/${HOSTNAME}-${FDAY}-system-fix-dovecot-utf8-all.txt

ls -all /home/*/mail/*/*/subscriptions | awk -F"/" '{ print $6,$5 }' | sed s/\ /\@/g >${TXT}
while read list; do
    echo $list
    ./cp_email_fix_dovecot_utf8 $list
done <${TXT}

_msg "[$1] File ${Yellow}${TXT}${Normal}"
