#!/bin/bash
# Description: cPanel System Queue Max Limit Hourly
# Arguments:
set -e

_tool _cp
_domain ${DOMAIN}
local ACCOUNT=${account}
local PATH_LIMITS=/var/cpanel/email_send_limits

if [ -f ${PATH_LIMITS}/hourly_notify/${DOMAIN} ]; then
    _run "[$1] Remove Max Deffer Daily ${Yellow}${DOMAIN}${Normal}" rm -rf ${PATH_LIMITS}/hourly_notify/${DOMAIN}
else
    _msg "[$1] File Email Send Limits ${Yellow}${DOMAIN}${Normal} ${Blue}-->${Normal} ${Red}does not exist${Normal}."
fi
