#!/bin/bash
# Description: cPanel System Fix Quota [All]
# Arguments:
set -e

local TXT01=/tmp/${HOSTNAME}-${FDAY}-account
local TXT02=/tmp/${HOSTNAME}-${FDAY}-account-quota
local TXT03=/tmp/${HOSTNAME}-${FDAY}-account-quota-not-found

ls /home/*/etc/*/quota | cut -d'/' -f3 | sort -n >${TXT02}
cat /etc/userdomains | awk '{print $2}' | sort -n | sed '/nobody/d' >${TXT01}
diff -u ${TXT02} ${TXT01} | grep -E '^\+' | sed 's/^+//g' | sed '1d' >${TXT03}

while IFS= read -r line; do
    domain=$(cat /etc/userdomains | grep $line | cut -d: -f1)
    touch /home/$line/etc/$domain/quota
    chown $line.mail /home/$line/etc/$domain/quota
    _msg "[$1] Quota ${Yellow}$line${Normal} ${Blue}-->${Normal} ${Color01}Done${Normal}"
done <${TXT03}
