#!/bin/bash
# Description: cPanel System Check DKIM [All]
# Arguments:
set -e

_tool _cp

local TXT=/tmp/${HOSTNAME}-${FDAY}-system-check-dkim.txt
sed "s|:||g" /etc/userdomains | awk '!/^\* nobody/{print $1, $2 | "sort | uniq" }' >${TXT}
while read domain account; do
    STATUS=$(whmapi1 --output=jsonpretty validate_current_dkims domain=$domain | jq '.data.payload | .[].state')
    _run "[dkim] $domain - $STATUS." echo $domain - $STATUS
done <${TXT}
