#!/bin/bash
# Description: cPanel System Get All Email
# Arguments:
set -e

_tool _cpanel

TEMPEMAILALL=/tmp/${TEMPTEMP}-all-email-account.txt
>$TEMPEMAILALL

CP_ACCOUNTS=$(ls -1A /var/cpanel/users/)

for user in $(echo -n $CP_ACCOUNTS); do
    domain=$(grep -i ^dns /var/cpanel/users/$user | cut -d= -f2)
    for dom in $(echo -n "$domain"); do
        PASSWD_FILE="/home/$user/etc/$dom/passwd"
        if [ -f $PASSWD_FILE ] && [ -s $PASSWD_FILE ]; then
            for mail in $(cat $PASSWD_FILE | cut -d":" -f1); do
                echo "$mail@$dom" >>${TEMPEMAILALL}
            done
        fi
    done
done

TOTAL_EMAIL=$(cat ${TEMPEMAILALL} | wc -l)

_run "[email] total email ${yellow}${TOTAL_EMAIL}${normal}" cat ${TEMPEMAILALL} | wc -l
