#!/bin/bash
# Description: cPanel System Backup Rclone (OneDrive)
# Arguments:
set -e

_tool _cp

DATEDETE=$(date --date='3 day ago' +%Y-%m-%d)
BACKUP_DIR="/backup/$ALIAS_HOSTNAME/$DATE"
LOG_RCLONE=/var/log/rclone.log
CMD_RCLONE=$(which rclone)
SECONDS=0

size=$(du -sh $BACKUP_DIR | awk '{ print $1}')

_msg "[$1] Preparing to copy backup on Server to OneDrive, please wait ... "
sleep 3
${CMD_RCLONE} copy $BACKUP_DIR "backup:Backup/cPanel/$ALIAS_NAME/$DATE" >>${LOG_RCLONE} 2>&1 #Copy all folders
_msg "${Blue}--> ${Normal}${Green}Done${Normal}"

_msg "[$1] Preparing to clean up backup older than 3 day on OneDrive, please wait ... "
sleep 3
${CMD_RCLONE} delete "backup:Backup/cPanel/$ALIAS_NAME/$DATEDETE" >>/${LOG_RCLONE} 2>&1 #Remove all file on folders older than 3 day
${CMD_RCLONE} rmdirs "backup:Backup/cPanel/$ALIAS_NAME/$DATEDETE" >>/${LOG_RCLONE} 2>&1 #Remove all empty folders older than 3 day
_msg "${Blue}--> ${Normal}${Green}Done${Normal}"

duration=$SECONDS
_msg "[$1] Total $size, $(($duration / 60)) minutes and $(($duration % 60)) seconds elapsed." >>/${LOG_RCLONE} 2>&1
