#!/bin/bash
# Description: cPanel System Fix Unlink [All]
# Arguments:
set -e

_tool _cp

local TXT=/tmp/${HOSTNAME}-${FDAY}-system-fix-unlink-all.txt

ls -all /home/*/mail/ | awk '$9 ~ /@/' | awk '{print $9, $11;}' | cut -d'/' -f1 >${TXT}

while read Email Domain; do
    Account=$(/scripts/whoowns $1)
    _msg "[$1] $Email - $Domain - $Account"
    DIR=/home/${Account}/mail/

    if [ -d "${DIR}" ]; then
        cd ${DIR}
        _run "[$1] Unlink ${Yellow}${Email}${Normal}" unlink $Email
    else
        _msg "[$1] ${Yellow}${Email}${Normal} ${Blue}-->${Normal} ${Red}DOES NOT EXIST${Normal}."
    fi
done <${TXT}
