#!/bin/bash
# Description: cPanel System Fix 2 Indentities [All]
# Arguments:
set -e

_tool _cpanel

TEMP_2_INDENTITIES=/tmp/${HOSTNAME}-${TEMPTEMP}-system-fix-2-indentities.txt

ls -1A /home/*/etc/*/*.rcube.db >${TEMP_2_INDENTITIES}
while read list; do
    _run "[fix] Backup ${yellow}${list}.${TEMPTEMP}${normal}" cp $list{,.${TEMPTEMP}}
    _run "[fix] Fix DB ${yellow}${list}${normal}" sqlite3 $list 'DELETE FROM identities WHERE identity_id = 2;'
done <${TEMP_2_INDENTITIES}
