#!/bin/bash
# Description: Demo Description
# Arguments:
set -e

_tool _cp
_domain ${DOMAIN}
local ACCOUNT=${account}

# while true; do
#     _msg "${Darkgray}Test${Normal}"
#     sleep 1
# done

_run "[$1] ls -all" ls -all
