#!/bin/bash
# Description: Test Description
# Arguments: Test Arguments
set -Eeo pipefail

[[ -z "${DOMAIN:-}" ]] && _die "[${Red}Missing${Normal}] ${Yellow}DOMAIN${Normal} --> ${Blue}Is Empty${Normal}"

while true; do
    _msg "${Darkgray}Test${Normal}"
    sleep 1
done

_msg "${Green}Xin ${Bold}Chào${Normal}"
_run "[$1] List folder" ls -all
