#!/bin/bash
# Description: Git Version Control
set -e

_tool _ins

_install git git-core/ppa

function _git {
    local repo=$1
    local dest=$2
    if ! test -d "$dest"; then
        _run "[$1] Clone ${Yellow}$repo${Normal} to ${Yellow}$dest${Normal}" git clone --recursive $1 $2
    else
        _msg "[$1] ${Yellow}$dest${Normal} already installed, skipping."
    fi
}
