#!/bin/bash
# Description: IceWarp Account Create
# Arguments: --domain=DOMAIN
set -e

_tool _iw

[[ -z "${DOMAIN:-}" ]] && _die "[$1] ${Yellow}DOMAIN${Normal} ${Blue}-->${Normal} ${Red}DOES NOT EXIST${Normal}."

local __domain=$(${IW_TOOL} export domain $DOMAIN | tr -d ',' | awk '!/not found/')
if [ -z $__domain ]; then
    _msg "[$1] ${Yellow}DOMAIN${Normal} ${Blue}-->${Normal} ${Yellow}OK${Normal}."
    PS3="[$1] Enter a plan: "
    select plan in "${PACKAGES[@]}"; do
        _msg "[$1] Selected plan: ${Yellow}$plan${Normal}"
        _run "[$1] Create domain: ${Yellow}$DOMAIN${Normal}" ${IW_TOOL} -m Email${plan} create domain $DOMAIN
        _run "[$1] Create email admin: ${Yellow}admin@$DOMAIN${Normal}" ${IW_TOOL} create account admin@$DOMAIN U_Password $PASSWORD U_DomainAdmin 1 U_Name "Admin ($DOMAIN)"
        echo "\n- Thông tin email domain: $DOMAIN ($plan)"
        echo "WebAdmin: https://mail.$DOMAIN/admin/"
        echo "WebMail: https://mail.$DOMAIN/webmail/"
        echo "User: admin@$DOMAIN"
        echo "Password: $PASSWORD\n"
        echo "- Vui lòng đổi mật khẩu sau lần đăng nhập đầu tiên (Options > Account > Change password)"
        echo "- Lưu ý: mật khẩu không được trùng với tên email, tối thiểu 6 ký tự (bao gồm chữ và số)"
        break
    done
else
    _msg "[$1] ${Yellow}$DOMAIN${Normal} is already used, skipping."
    exit_with_error
fi
