#!/bin/bash
# Description: IceWarp Account Create
# Arguments: --domain=DOMAIN
set -e

_tool _iw
local TXT=/tmp/${DOMAIN}-${FDAY}-acc-create.txt

[[ -z "${DOMAIN:-}" ]] && _die "[$1] ${Yellow}DOMAIN${Normal} ${Blue}-->${Normal} ${Red}DOES NOT EXIST${Normal}."

local __domain=$(${IW_TOOL} export domain $DOMAIN | tr -d ',' | awk '!/not found/')
if [ -z $__domain ]; then
    _msg "[$1] ${Yellow}DOMAIN${Normal} ${Blue}-->${Normal} ${Yellow}OK${Normal}."
    PS3="[$1] Enter a plan: "
    select plan in "${PACKAGES[@]}"; do
        _msg "[$1] Selected plan: ${Yellow}$plan${Normal}"
        _run "[$1] Create domain: ${Yellow}$DOMAIN${Normal}" ${IW_TOOL} -m Email${plan} create domain $DOMAIN
        _run "[$1] Create email admin: ${Yellow}admin@$DOMAIN${Normal}" ${IW_TOOL} create account admin@$DOMAIN U_Password $PASSWORD U_DomainAdmin 1 U_Name "Admin ($DOMAIN)"
        echo "" >${TXT}
        echo "- Thông tin email domain: $DOMAIN ($plan)" >>${TXT}
        echo "WebAdmin: https://mail.$DOMAIN/admin/" >>${TXT}
        echo "WebMail: https://mail.$DOMAIN/webmail/" >>${TXT}
        echo "User: admin@$DOMAIN" >>${TXT}
        echo "Password: $PASSWORD" >>${TXT}
        echo "- Vui lòng đổi mật khẩu sau lần đăng nhập đầu tiên (Options > Account > Change password)" >>${TXT}
        echo "- Lưu ý: mật khẩu không được trùng với tên email, tối thiểu 6 ký tự (bao gồm chữ và số)" >>${TXT}
        echo "" >>${TXT}
        _msg "[$1] Info ${Yellow}$TXT${Normal}"
        cat ${TXT}
        break
    done
else
    _msg "[$1] ${Yellow}$DOMAIN${Normal} is already used, skipping."
    exit_with_error
fi
