#!/bin/bash
# Description: Linux SSH Config
# Arguments:
set -e

_SSH_CONFIG=$(netstat -l | awk '/0:3090/ {print $4}')
_SSH_CONFIG_PATH=/etc/ssh/sshd_config

_command netstat

if [ -z ${_SSH_CONFIG} ]; then
    _msg "[$1] Port ${Yellow}3090${Normal} is ${Green}UNUSED${Normal}"
    _copy ${_SSH_CONFIG_PATH}
    # _run "[$1] Config SSH Port 3090" awk -i inplace '/Port / {gsub("^.*","Port 3090", $0)}1' $_SSH_CONFIG_PATH
    _run "[$1] Config SSH Port 3090" sed -i "s/$(grep "Port " /etc/ssh/sshd_config)/Port 3090/g" $_SSH_CONFIG_PATH
    _run "[$1] Service SSHD restart " systemctl restart sshd
else
    _msg "[$1] Port ${Yellow}3309${Normal} is already used, skipping."
    exit_with_error
fi
