#!/bin/bash
# Description: Linux SSH Config
# Arguments:
set -e

_SSH_CONFIG=$(netstat -l | awk '/0:3090/ {print $4}')
_SSH_CONFIG_PATH=/etc/ssh/sshd_config

if command -v netstat; then
    _msg "[$1] Command ${Yellow}netstat${Normal} ${Blue}-->${Normal} ${Yellow}OK${Normal}"
else
    _msg "[$1] ${Yellow}netstat${Normal} --> ${Red}does not exist${Normal}."
    exit_with_error
fi

if [ -z ${_SSH_CONFIG} ]; then
    _msg "[$1] Port ${Yellow}3090${Normal} is unused"
    _run "[$1] File ${Yellow}${_SSH_CONFIG_PATH}.${FDAY}${Normal}" cp ${_SSH_CONFIG_PATH}{,.${FDAY}}
    _run "[$1] Config SSH Port 3090" awk -i inplace '/Port / {gsub("^.*","Port 3090", $0)}1' /etc/ssh/sshd_config
    _run "[$1] Restart service SSH" systemctl restart sshd
else
    _msg "[$1] Port ${Yellow}3309${Normal} is already used, skipping"
    exit_with_error
fi
