#!/bin/bash
# Description: Terminal config BASH
set -e

function _bash_aliases {
    local file=$1
    cat >${file} <<EOF
alias ls="ls --color -h --group-directories-first"
alias ll="ls --color -l -h --group-directories-first"
alias lla="ll -a"
alias sysrun="systemctl | head -1; systemctl | grep running"
EOF
}

function _bashrc_config {
    local name=$1
    cat >>~/.bashrc <<EOF

# Bash custom config
if [ -f ~/${name} ]; then
    . ~/${name}
fi
EOF
}

local NAME=".bash_haiht"
local FILE=${HOME}/${NAME}

if [ -f ${FILE} ]; then
    # Found
    _copy ${FILE}
    _run "[$1] Add config alias ~/${NAME}" _bash_aliases ${FILE}
else
    # Not Found
    _run "[$1] Add config alias ~/${NAME}" _bash_aliases ${FILE}
fi

if grep -q "${NAME}" "${HOME}/.bashrc"; then
    # Found
    _msg "[$1] ~/${NAME} found on ~/.bashrc ... skipping."
else
    # Not Found
    _run "[$1] Add config to ~/.bashrc" _bashrc_config ${NAME}
    RESTART_SHELL=1
fi
