#!/bin/bash
# Description: Terminal config TMUX
set -e

function _tmux_config {
    local file=$1
    cat >${file} <<EOF
set-option -g default-terminal "xterm-256color"
EOF
}

local NAME=".tmux.conf"
local FILE=${HOME}/${NAME}

if [ -f ${FILE} ]; then
    _msg "[$1] File ~/${NAME} found ... ${Yellow}skipping${Normal}"
else
    _msg "[$1] File ~/${NAME} not found"
    _run "[$1] Add config tmux ~/${NAME}" _tmux_config ${FILE}
fi
