#!/bin/bash
# Description: Terminal config TMUX
set -e

function _tmux_config {
    local file=$1
    cat >${file} <<EOF
set-option -g default-terminal "xterm-256color"
set -g mode-mouse on
EOF
}

local NAME=".tmux.conf"
local FILE=${HOME}/${NAME}

if [ -f ${FILE} ]; then
    # Found
    _copy ${FILE}
    _run "[$1] Add config tmux ~/${NAME}" _tmux_config ${FILE}
else
    # Not Found
    _run "[$1] Add config tmux ~/${NAME}" _tmux_config ${FILE}
fi
