#!/bin/bash
# Description: Vim config
set -e

function _vim_config {
  local file=$1
  cat >${file} <<EOF
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

call plug#begin('~/.vim/plugged')
  Plug 'tpope/vim-surround'
  Plug 'mbbill/undotree'
call plug#end()

set nocompatible               " be improved
filetype plugin indent on      " enable file detection and plugins
syntax on                      " enable syntax highlighting
set encoding=UTF-8             " set default encoding top utf-8
set pumheight=15               " makes popup menu smaller
set ruler                      " show the cursor position all the time
set iskeyword+=-               " treat dash separated words as a word text object
set t_Co=256                   " support 256 colors
set conceallevel=0             " so that i can see $() in markdown files
set smarttab                   " makes tabbing smarter will realize you have 2 vs 4
set autoindent                 " preverse indentation
set smartindent                " smart indentation for languages
set laststatus=0               " always display the status line
set mouse=i                    " enable mouse suppor
set hlsearch                   " highlight all search patterns
set incsearch                  " enable incremental search
set hidden                     " navigate to another buffer  without saving current buffer
set fdm=indent                 " set fold method to indent "
set foldlevelstart=99          " fold level when open a file (make all fold open)
set ignorecase                 " case insensitive search by default
set smartcase                  " case sensitive search when using upppercase characters
set splitbelow splitright      " set default position for where a split open
set updatetime=300             " faster completion
set timeoutlen=500             " by default timeoutlen is 1000s
set scrolloff=3                " set x lines to the cursor when moving vertically
set showcmd                    " set command keys pressed
set wildmenu                   " enable wild menu
set wildmode=longest:full,full " shell-like autocomplete to unambiguous portion
set backspace=eol,start,indent " backspace works on insert mode
set showmatch                  " show matching brackets when text indicator is over them
set noerrorbells novisualbell  " no annoying sound on errors
set noswapfile                 " disable swap file
set nowrap                     " disable wrap
set fileformats=unix,dos,mac   " use unix as the standard file type
set autoread                   " autoread a file when it is changed from the outside
set fileignorecase             " ignore case when autocompletes when browsing files
set wrapscan                   " search, wrap around the end of the buffer
set magic                      " for regular expressions turn magic on
set maxmempattern=1000         " maximum amount of memory in Kbyte used for pattern matching
set expandtab                  " use space for tab

" NO ONE IS REALLY HAPPY UNTIL YOU HAVE THIS SHORTCUTS
cnoreabbrev W! w!
cnoreabbrev Q! q!
cnoreabbrev Qall! qall!
cnoreabbrev Wq wq
cnoreabbrev Wa wa
cnoreabbrev wQ wq
cnoreabbrev WQ wq
cnoreabbrev W w
cnoreabbrev Q q
cnoreabbrev Qall qall

au! BufWritePost $MYVIMRC source %
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

nnoremap <F2> :set paste<cr>
nnoremap <silent> <F12> :UndotreeToggle<cr>
EOF
}

local NAME=".vimrc"
local FILE=${HOME}/${NAME}

if [ -f ${FILE} ]; then
  echo "[vim] File ~/${NAME} found ... ${yellow}skipping${normal}"
else
  echo "[vim] File ~/${NAME} not found"
  _run "[vim] Add config vim ~/${NAME}" _vim_config ${FILE}
fi

_run "[vim] Install plugins" vim +PlugInstall +qa
